// Generated by LiveScript 1.3.1
'use strict';
var socket, vote, unvote, join, me, user;
socket = require('socket.io-client')();
socket.on('news', console.log.bind(console));
vote = function(vid){
  return socket.emit('vote', {
    uid: me,
    vote: vid
  }, function(msg){
    return console.log(msg);
  });
};
unvote = function(vid){
  return socket.emit('vote', {
    uid: me,
    unvote: vid
  }, function(msg){
    return console.log(msg);
  });
};
join = function(user){
  return socket.emit('join', user, function(uuid){
    var me;
    localStorage.setItem('uuid', uuid);
    me = uuid;
    return console.log(me);
  });
};
me = localStorage.getItem('uuid');
user = {
  name: '小宇哥'
};
if (me) {
  socket.emit('back', me, function(msg){
    return console.log(msg);
  });
} else {
  join(user);
}
window.socket = socket;
window.vote = vote;
window.unvote = unvote;